config/routes.rb
Lobsters::Application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"

    get "/u" => "users#tree"
    get "/u/:username" => redirect { |params| "@#{params[:username]}" }
    get "/@:username" => "users#show", :as => "user", :format => /html|json/

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :recipient,
    :class_name => "User",
    :foreign_key => "recipient_user_id"
  belongs_to :author,
    :class_name => "User",
    :foreign_key => "author_user_id"

  validates_presence_of :recipient
  validates_presence_of :author

  attr_accessor :recipient_username

  validates_length_of :subject, :in => 1..150
  validates_length_of :body, :maximum => (64 * 1024)

  scope :unread, -> { where(:has_been_read => false,
    :deleted_by_recipient => false) }

  before_validation :assign_short_id,
    :on => :create
  after_create :deliver_email_notifications
  after_save :update_unread_counts
  after_save :check_for_both_deleted

  def assign_short_id
    self.short_id = ShortId.new(self.class).generate
  end

  def check_for_both_deleted
    if self.deleted_by_author? && self.deleted_by_recipient?
      self.destroy
    end
  end

  def update_unread_counts
    self.recipient.update_unread_message_count!
  end

  def deliver_email_notifications
    return if Rails.env.development?

    if self.recipient.email_messages?
      begin
        EmailMessage.notify(self, self.recipient).deliver
      rescue => e
        Rails.logger.error "error e-mailing #{self.recipient.email}: #{e}"
      end
    end

    if self.recipient.pushover_messages?
      self.recipient.pushover!({
        :title => "#{Rails.application.name} message from " <<
          "#{self.author.username}: #{self.subject}",
        :message => self.plaintext_body,
        :url => self.url,
        :url_title => "Reply to #{self.author.username}",
      })
    end
  end

  def recipient_username=(username)
    self.recipient_user_id = nil

    if u = User.where(:username => username).first
      self.recipient_user_id = u.id
      @recipient_username = username
    else
      errors.add(:recipient_username, "is not a valid user")
    end
  end

  def linkified_body
    Markdowner.to_html(self.body)
  end

  def plaintext_body
    # TODO: linkify then strip tags and convert entities back
    self.body.to_s
  end

  def url
    Rails.application.root_url + "messages/#{self.short_id}"
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_filter :require_logged_in_user
  before_filter :find_message, :only => [ :show, :destroy, :keep_as_new ]

  def index
    @cur_url = "/messages"
    @title = "Messages"

    @new_message = Message.new

    @direction = :in
    @messages = @user.undeleted_received_messages

    if params[:to]
      @new_message.recipient_username = params[:to]
    end
  end

  def sent
    @cur_url = "/messages"
    @title = "Messages Sent"

    @direction = :out
    @messages = @user.undeleted_sent_messages

    @new_message = Message.new

    render :action => "index"
  end

  def create
    @cur_url = "/messages"
    @title = "Messages"

    @new_message = Message.new(message_params)
    @new_message.author_user_id = @user.id

    @direction = :out
    @messages = @user.undeleted_received_messages

    if @new_message.save
      flash[:success] = "Your message has been sent to " <<
        @new_message.recipient.username.to_s << "."
      return redirect_to "/messages"
    else
      render :action => "index"
    end
  end

  def show
    @cur_url = "/messages"
    @title = @message.subject

    @new_message = Message.new
    @new_message.recipient_username = (@message.author_user_id == @user.id ?
      @message.recipient.username : @message.author.username)

    if @message.recipient_user_id == @user.id
      @message.has_been_read = true
      @message.save
    end

    if @message.subject.match(/^re:/i)
      @new_message.subject = @message.subject
    else
      @new_message.subject = "Re: #{@message.subject}"
    end
  end

  def destroy
    if @message.author_user_id == @user.id
      @message.deleted_by_author = true
    end

    if @message.recipient_user_id == @user.id
      @message.deleted_by_recipient = true
    end

    @message.save!

    flash[:success] = "Deleted message."

    if @message.author_user_id == @user.id
      return redirect_to "/messages/sent"
    else
      return redirect_to "/messages"
    end
  end

  def batch_delete
    deleted = 0

    params.each do |k,v|
      if v.to_s == "1" && m = k.match(/^delete_(.+)$/)
        if (message = Message.where(:short_id => m[1]).first)
          ok = false
          if message.author_user_id == @user.id
            message.deleted_by_author = true
            ok = true
          end
          if message.recipient_user_id == @user.id
            message.deleted_by_recipient = true
            ok = true
          end

          if ok
            message.save!
            deleted += 1
          end
        end
      end
    end

    flash[:success] = "Deleted #{deleted} message#{deleted == 1 ? "" : "s"}."

    @user.update_unread_message_count!

    return redirect_to "/messages"
  end

  def keep_as_new
    @message.has_been_read = false
    @message.save

    return redirect_to "/messages"
  end

private
  def message_params
    params.require(:message).permit(
      :recipient_username, :subject, :body,
    )
  end

  def find_message
    if @message = Message.where(:short_id => params[:message_id] ||
    params[:id]).first
      if (@message.author_user_id == @user.id ||
      @message.recipient_user_id == @user.id)
        return true
      end
    end

    flash[:error] = "Could not find message."
    redirect_to "/messages"
    return false
  end
end

app/views/messages/index.html.erb
<script>
  $(document).ready(function() {
    $("#delete_all").click(function(e) {
      var table = $(e.target).closest("table");
      $("td input:checkbox", table).attr("checked", e.target.checked);
    });
  });
</script>

<div class="box wide">
  <div class="legend" style="float: right;">
    <% if @direction == :out %>
      <a href="/messages">View Received</a>
    <% else %>
      <a href="/messages/sent">View Sent</a>
    <% end %>
  </div>

  <h1 class="legend">
    Private Messages
    <% if @direction == :out %>
      Sent
    <% end %>
  </h1>

  <% if @messages.any? %>
    <%= form_tag batch_delete_messages_path do %>
      <table class="data zebra" width="100%" cellspacing=0>
      <tr>
        <th width="3%"><%= check_box_tag "delete_all",
          :id => "delete_all" %></th>
        <th width="15%"><%= @direction == :in ? "From" : "To" %></th>
        <th width="17%"><%= @direction == :in ? "Received" : "Sent" %></th>
        <th width="60%">Subject</th>
      </tr>
      <% @messages.includes(:author, :recipient).each do |message| %>
        <tr class="<%= message.has_been_read? ? "" : "bold" %>">
          <td><%= check_box_tag "delete_#{message.short_id}" %></td>
          <td><% if @direction == :in %>
              <a href="/u/<%= message.author.username %>"><%=
                message.author.username %></a>
            <% else %>
              <a href="/u/<%= message.recipient.username %>"><%=
                message.recipient.username %></a>
            <% end %></td>
          <td><%= time_ago_in_words_label(message.created_at) %> ago</td>
          <td><a href="/messages/<%= message.short_id %>"><%= message.subject
            %></a></td>
        </tr>
      <% end %>
      </table>
      <p>
      <%= submit_tag "Delete Selected" %>
      </p>
    <% end %>
  <% else %>
    <p>
    You do not have any <%= @direction == :in ? "" : "sent" %> private
      messages.
    </p>
  <% end %>

  <br>

  <h2 class="legend">
    Compose Message
  </h2>

  <%= form_for @new_message, :method => :post do |f| %>
    <%= error_messages_for @new_message %>

    <div class="boxline">
      <%= f.label :recipient_username, "To:", :class => "required" %>
      <%= f.text_field :recipient_username, :size => 20,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :subject, "Subject:", :class => "required" %>
      <%= f.text_field :subject, :style => "width: 500px;",
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.label :body, "Message:", :class => "required" %>
      <%= f.text_area :body, :style => "width: 500px;", :rows => 5,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <p></p>
      <%= submit_tag "Send Message" %>
    </div>
  <% end %>
</div>

app/views/messages/show.html.erb
<div class="box wide">
  <div class="legend" style="float: right;">
    <% if @message.author_user_id == @user.id %>
      <a href="/messages/sent">Back to Sent Messages</a>
    <% else %>
      <a href="/messages">Back to Messages</a>
    <% end %>
  </div>

  <div class="legend">
    <h1 class="media-heading"><%= @message.subject %></h1>

    <div class="sublegend text-muted">
      Sent from <a href="/u/<%= @message.author.username %>"><%=
        @message.author.username %></a>
      <% if @message.author.is_admin? %>
        (administrator)
      <% elsif @message.author.is_moderator? %>
        (moderator)
      <% end %>
      to
      <a href="/u/<%= @message.recipient.username %>"><%=
        @message.recipient.username %></a>
      <%= time_ago_in_words_label(@message.created_at) %> ago
    </div>
  </div>

  <br/>

  <div class="boxline comment_text">
    <%= raw @message.linkified_body %>
  </div>

  <br>

  <div class="boxline">
    <div style="float: left;">
      <%= form_tag message_path(@message.short_id), :method => :delete do %>
        <%= submit_tag "Delete Message" %>
      <% end %>
    </div>

    <div style="float: left; padding-left: 1em;">
      <%= form_tag message_path(@message.short_id) + "/keep_as_new",
      :method => :post do %>
        <%= submit_tag "Keep As New" %>
      <% end %>
    </div>
  </div>

  <div style="clear: both;"></div>

  <hr/>

  <h2 class="legend">
    Compose Reply To <%= @new_message.recipient_username %>
  </h2>

  <%= form_for @new_message, :method => :post do |f| %>
    <%= f.hidden_field :recipient_username %>

    <%= error_messages_for @new_message %>

    <div class="boxline">
      <%= f.text_field :subject, :style => "width: 500px;",
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <%= f.text_area :body, :style => "width: 500px;", :rows => 5,
        :autocomplete => "off" %>
    </div>

    <div class="boxline">
      <p></p>
      <%= submit_tag "Send Message" %>
    </div>
  <% end %>
</div>