config/routes.rb
Lobsters::Application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"

    get "/u" => "users#tree"
    get "/u/:username" => redirect { |params| "@#{params[:username]}" }
    get "/@:username" => "users#show", :as => "user", :format => /html|json/

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/controllers/settings_controller.rb
class SettingsController < ApplicationController
  before_filter :require_logged_in_user

  def index
    @title = "Account Settings"

    @edit_user = @user.dup
  end

  def delete_account
    if @user.try(:authenticate, params[:user][:password].to_s)
      @user.delete!
      reset_session
      flash[:success] = "Your account has been deleted."
      return redirect_to "/"
    end

    flash[:error] = "Your password could not be verified."
    return redirect_to settings_path
  end

  def pushover
    if !Pushover.SUBSCRIPTION_CODE
      flash[:error] = "This site is not configured for Pushover"
      return redirect_to "/settings"
    end

    session[:pushover_rand] = SecureRandom.hex

    return redirect_to Pushover.subscription_url({
      :success => "#{Rails.application.root_url}settings/pushover_callback?" <<
        "rand=#{session[:pushover_rand]}",
      :failure => "#{Rails.application.root_url}settings/",
    })
  end

  def pushover_callback
    if !session[:pushover_rand].to_s.present?
      flash[:error] = "No random token present in session"
      return redirect_to "/settings"
    end

    if !params[:rand].to_s.present?
      flash[:error] = "No random token present in URL"
      return redirect_to "/settings"
    end

    if params[:rand].to_s != session[:pushover_rand].to_s
      raise "rand param #{params[:rand].inspect} != " <<
        session[:pushover_rand].inspect
    end

    @user.pushover_user_key = params[:pushover_user_key].to_s
    @user.save!

    if @user.pushover_user_key.present?
      flash[:success] = "Your account is now setup for Pushover notifications."
    else
      flash[:success] = "Your account is no longer setup for Pushover " <<
        "notifications."
    end

    return redirect_to "/settings"
  end

  def update
    @edit_user = @user.clone

    if @edit_user.update_attributes(user_params)
      flash.now[:success] = "Successfully updated settings."
      @user = @edit_user
    end

    render :action => "index"
  end

private

  def user_params
    params.require(:user).permit(
      :username, :email, :password, :password_confirmation, :about,
      :email_replies, :email_messages, :email_mentions,
      :pushover_replies, :pushover_messages, :pushover_mentions,
      :mailing_list_mode, :show_avatars
    )
  end
end

app/views/settings/index.html.erb
<div class="col-sm-12">
  <div class="row">
    <h1 class="legend col-sm-6">
      Account Settings
    </h1>

    <div class="col-sm-6 text-right">
      <a href="/u/<%= @user.username %>">View Profile</a>
    </div>
  </div>

    <%= form_for @edit_user, :url => settings_path, :method => :post,
    :html => { :id => "edit_user", class: 'form-horizontal' } do |f| %>
      <%= error_messages_for f.object %>

      <div class="form-group">
        <%= f.label :username, "Username:", :class => "required control-label col-sm-2" %>
        <div class="col-sm-10">
          <%= f.text_field :username, :size => 15, class: 'form-control', style: 'max-width: 200px' %>

          <p class="help-block">
            Only letters, numbers, dashes and underscores allowed. Up to 24 chars.
          </p>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password, "New Password:", :class => "required control-label col-sm-2" %>
        <div class="col-sm-3">
          <%= f.password_field :password, :size => 40, :autocomplete => "off", class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :password_confirmation, "Confirm Password:",
          :class => "required control-label col-sm-2" %>
        <div class="col-sm-3">
          <%= f.password_field :password_confirmation, :size => 40,
            :autocomplete => "off", class: 'form-control' %>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :email, "E-mail Address:", :class => "required control-label col-sm-2" %>
        <div class="col-sm-10">
          <div class="row">
            <div class="col-sm-4">
              <%= f.text_field :email, :size => 40, class: 'form-control' %>
            </div>

            <div class="col-sm-7">
              <p class="help-block">
                <a href="http://www.gravatar.com/" target="_blank">Gravatar</a>'ized
              </p>
            </div>
          </div>
        </div>
      </div>

      <div class="form-group">
        <%= f.label :about, "About:", :class => "required col-sm-2 control-label" %>
        <div class="col-sm-10">
          <%= f.text_area :about, :size => "100x5", class: 'form-control' %>

          <div class="help-block boxline markdown_help_toggler">
            <div class="markdown_help_label">
              Markdown formatting available
            </div>

            <div style="clear: both;"></div>

            <%= render :partial => "global/markdownhelp" %>
          </div>

        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit "Save Account Settings", class: 'btn btn-primary' %>
        </div>
      </div>

      <br/>
      <br/>

      <fieldset class="hidden">
        <legend>
          Notification Settings
        </legend>

        <div class="form-group">
          <%= f.label :pushover_user_key,
            raw("<a href=\"https://pushover.net/\">Pushover</a>:"),
            :class => "required col-sm-2 control-label" %>

          <div class="col-sm-10">
            <p class="form-control-static"><%= link_to((f.object.pushover_user_key.present??
              "Manage Pushover Subscription" : "Subscribe With Pushover"),
              "/settings/pushover", :class => "pushover_button", :method => :post) %></p>

            <p class="help-block">
              For optional comment and message notifications below
            </p>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>
          Comment Reply Notification Settings
        </legend>

        <div class="form-group">
          <%= f.label :email_replies, "Receive E-mail:", :class => "required control-label col-sm-2" %>
          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :email_replies %>
              </label>
            </div>
          </div>
        </div>

        <div class="form-group hidden">
          <%= f.label :pushover_replies, "Receive Pushover Alert:",
            :class => "required control-label col-sm-2" %>

          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :pushover_replies %>
                Requires user key entered above
              </label>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>
          Comment Mention Notification Settings
        </legend>

        <div class="form-group">
          <%= f.label :email_mentions, "Receive E-mail:", :class => "required col-sm-2 control-label" %>
          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :email_mentions %>
              </label>
            </div>
          </div>
        </div>

        <div class="form-group hidden">
          <%= f.label :pushover_mentions, "Receive Pushover Alert:",
            :class => "required col-sm-2 control-label" %>

          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :pushover_mentions %>
                Requires user key entered above
              </label>
            </div>
        </div>
      </fieldset>


      <fieldset>
        <legend>
          Private Message Notification Settings
        </legend>

        <div class="form-group">
          <%= f.label :email_messages, "Receive E-mail:", :class => "required col-sm-2 control-label" %>
          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :email_messages %>
              </label>
            </div>
          </div>
        </div>

        <div class="form-group hidden">
          <%= f.label :pushover_messages, "Receive Pushover Alert:",
            :class => "required col-sm-2 control-label" %>

          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :pushover_messages %>
                Requires user key entered above
              </label>
            </div>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>
          Mailing List Settings
        </legend>

        <p class="text-muted">
        When enabled, you will receive all newly submitted stories and comments to
        your e-mail address entered above, except those stories (and their
        comments) filtered by your <a href="/filters">tag filters</a>.  All e-mail
        messages will appear to be sent to your private list address shown below
        which you can filter on<span class="hidden">, and e-mails you send to that address will be
        posted under your account on this website</span>. You should keep your unique
        list address private<span class="hidden"> to prevent others from posting comments as you</span>.
        </p>

        <div class="form-group">
          <%= f.label :mailing_list_mode, "Receive List E-mails:",
            :class => "required col-sm-2 control-label" %>
          <div class="col-sm-4">
            <%= f.select :mailing_list_mode, [ [ "No e-mails", 0 ],
              [ "All stories and comments", 1 ], [ "Only stories", 2 ] ], {}, class: 'form-control' %>
          </div>
        </div>

        <div class="form-group hidden">
          <label class="required col-sm-2 control-label">List Address:</label>
          <div class="col-sm-10">
          <p class="form-control-static"><tt><%= Rails.application.shortname %>-<%=
            @edit_user.mailing_list_token %>@<%= Rails.application.domain %></tt></p>
          </div>
        </div>
      </fieldset>

      <fieldset>
        <legend>
          Miscellaneous Settings
        </legend>

        <div class="form-group">
          <%= f.label :show_avatars, "Show User Avatars:", :class => "required col-sm-2 control-label" %>

          <div class="col-sm-10">
            <div class="checkbox">
              <label>
                <%= f.check_box :show_avatars %>
              </label>
            </div>
          </div>
        </div>
      </fieldset>

      <div class="form-group">
        <div class="col-sm-10 col-sm-offset-2">
          <%= f.submit "Save All Settings", class: 'btn btn-primary' %>
        </div>
      </div>
    <% end %>

    <br/>
    <br/>
    <br/>

    <%= form_for @edit_user, :url => delete_account_path, :method => :post,
    :html => { :id => "delete_user", class: 'form-horizontal' } do |f| %>
      <fieldset>
        <legend>
          Delete Account
        </legend>

        <p class="text-muted">
        To permanently delete your account, verify your current password below.
        Your account will be put into a deleted state, your comments will be marked
        as deleted and no longer readable by any other users, and your private
        messages will be deleted.  Your submitted stories will not be deleted.
        Your username will remain reserved and will not be available to use on any
        other account.
        </p>

        <div class="form-group">
          <%= f.label :password, "Verify Password:", :class => "required col-sm-3 control-label" %>
          <div class="col-sm-3">
            <%= f.password_field :password, :size => 40, :autocomplete => "off", class: 'form-control' %>
          </div>
        </div>

        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <%= f.submit "Yes, Delete My Account", class: 'btn btn-danger' %>
          </div>
        </div>
      </fieldset>
    <% end %>

    <fieldset id="invite">
      <legend>
        Invite a New User
      </legend>

      <%= render :partial => "users/invitationform" %>
    </fieldset>
  </div>
</div>