config/routes.rb
Lobsters::Application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"

    get "/u" => "users#tree"
    get "/u/:username" => redirect { |params| "@#{params[:username]}" }
    get "/@:username" => "users#show", :as => "user", :format => /html|json/

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/models/invitation.rb
class Invitation < ActiveRecord::Base
  belongs_to :user

  validate do
    unless email.to_s.match(/\A[^@ ]+@[^ @]+\.[^ @]+\z/)
      errors.add(:email, "is not valid")
    end
  end

  before_validation :create_code,
    :on => :create

  def create_code
    (1...10).each do |tries|
      if tries == 10
        raise "too many hash collisions"
      end

      self.code = Utils.random_str(15)
      unless Invitation.exists?(:code => self.code)
        break
      end
    end
  end

  def send_email
    InvitationMailer.invitation(self).deliver
  end
end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_filter :require_logged_in_user,
    :except => [ :build, :create_by_request, :confirm_email ]

  def build
    if Rails.application.allow_invitation_requests?
      @invitation_request = InvitationRequest.new
    else
      flash[:error] = "Public invitation requests are not allowed."
      return redirect_to "/login"
    end
  end

  def index
    @invitation_requests = InvitationRequest.where(:is_verified => true)
  end

  def confirm_email
    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = "Invalid or expired invitation request"
      return redirect_to "/invitations/request"
    end

    ir.is_verified = true
    ir.save!

    flash[:success] = "Your invitation request has been validated and " <<
      "will now be shown to other logged-in users."
    return redirect_to "/invitations/request"
  end

  def create
    i = Invitation.new
    i.user_id = @user.id
    i.email = params[:email]
    i.memo = params[:memo]

    begin
      i.save!
      i.send_email
      flash[:success] = "Successfully e-mailed invitation to " <<
        params[:email].to_s << "."
    rescue
      flash[:error] = "Could not send invitation, verify the e-mail " <<
        "address is valid."
    end

    if params[:return_home]
      return redirect_to "/"
    else
      return redirect_to "/settings"
    end
  end

  def create_by_request
    if Rails.application.allow_invitation_requests?
      @invitation_request = InvitationRequest.new(
        params.require(:invitation_request).permit(:name, :email, :memo))

      @invitation_request.ip_address = request.remote_ip

      if @invitation_request.save
        flash[:success] = "You have been e-mailed a confirmation to " <<
          params[:invitation_request][:email].to_s << "."
        return redirect_to "/invitations/request"
      else
        render :action => :build
      end
    else
      return redirect_to "/login"
    end
  end

  def send_for_request
    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = "Invalid or expired invitation request"
      return redirect_to "/invitations"
    end

    i = Invitation.new
    i.user_id = @user.id
    i.email = ir.email

    i.save!
    i.send_email
    ir.destroy!
    flash[:success] = "Successfully e-mailed invitation to " <<
      ir.name.to_s << "."

    return redirect_to "/invitations"
  end

  def delete_request
    if !@user.is_moderator?
      return redirect_to "/invitations"
    end

    if !(ir = InvitationRequest.where(:code => params[:code].to_s).first)
      flash[:error] = "Invalid or expired invitation request"
      return redirect_to "/invitations"
    end

    ir.destroy!
    flash[:success] = "Successfully deleted invitation request from " <<
      ir.name.to_s << "."

    return redirect_to "/invitations"
  end
end

app/views/invitations/build.html.erb
<div class="col-sm-12">
  <h1 class="legend">
    Request an Invitation
  </h1>

  <p>
  If you don't know (or can't find) an <a href="/u/">existing user</a> from
  whom to request an invitation, you can make a public request for one.  This
  will display your name and memo to all other logged-in users who can then
  send you an invitation if they recognize you.
  </p>

  <p>
  Your e-mail address must be valid and confirmed by visiting a URL e-mailed to
  you before your request will be displayed.  Your e-mail address will not be
  shown to any other users (except moderators).
  </p>

  <br/>

  <%= form_for @invitation_request,
  :url => create_invitation_by_request_path, html: { class: 'form-horizontal' } do |f| %>

    <div class="form-group">
      <%= f.label :name, "Name:", class: 'control-label col-sm-2' %>

      <div class="col-sm-3">
        <%= f.text_field :name, :size => 30, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :email, "E-mail Address:", class: 'control-label col-sm-2' %>
      <div class="col-sm-3">
        <%= f.text_field :email, :size => 30, class: 'form-control' %>
      </div>
    </div>

    <div class="form-group">
      <%= f.label :memo, "URL:", class: 'control-label col-sm-2' %>
      <div class="col-sm-5">
        <%= f.text_field :memo, :size => 30, class: 'form-control' %>
      </div>
    </div>

    <div class="col-sm-offset-2">
      <p class="text-muted">URL to verify you (Personal website, Twitter account,
      etc.)</p>
    </div>

    <%= submit_tag "Request Invitation" %>
  <% end %>
</div>

app/views/invitations/index.html.erb
<div class="col-sm-12">
  <div class="box wide">
    <h1 class="legend">
      Requested Invitations
    </h1>

    <p>
    These persons have requested invitations and confirmed their e-mail
    addresses.  If you recognize anyone, feel free to send them an invitation and
    remove their request.  Spam will be cleared out by a moderator.
    </p>

    <table class="data table table-striped table-hover" width="100%" cellspacing=0>
    <tr>
      <th width="15%">Date/Time</th>
      <th width="20%">Name</th>
      <th width="39%">Memo</th>
      <th width="17%"></th>
      <% if @user.is_moderator? %>
        <th></th>
      <% end %>
    </tr>
    <% bit = 0 %>
    <% @invitation_requests.each do |ir| %>
      <tr class="row<%= bit %>">
        <td><%= ir.created_at.strftime("%Y-%m-%d %H:%M:%S") %></td>
        <td><%= ir.name %>
          <% if @user.is_moderator? %>
            <br>
            <em><%= ir.email %></em>
          <% end %></td>
        <td><%= raw ir.markeddown_memo %></td>
        <td><%= form_tag send_invitation_for_request_path do %>
          <%= hidden_field_tag "code", ir.code %>
          <%= submit_tag "Send Invitation", :data => { :confirm => "Are " <<
          "you sure you want to invite this person and remove this request?" }, class: 'btn btn-default' %>
        <% end %></td>
        <% if @user.is_moderator? %>
          <td><%= form_tag delete_invitation_request_path do %>
            <%= hidden_field_tag "code", ir.code %>
            <%= submit_tag "Delete", :data => { :confirm => "Are you sure " <<
              "you want to delete this request?" }, class: 'btn btn-default'  %>
          <% end %></td>
        <% end %>
      </tr>
      <% bit = (bit == 1 ? 0 : 1) %>
    <% end %>
    <% if @invitation_requests.count == 0 %>
      <tr>
        <td colspan=<%= @user.is_moderator?? 5 : 4 %> align="center"><span
          class="na">No invitation requests</span></td>
      </tr>
    <% end %>
    </table>
  </div>
</div>