config/routes.rb
Lobsters::Application.routes.draw do
  require 'sidekiq/web'

  mount Sidekiq::Web => '/sidekiq'

  scope :format => "html" do
    root :to => "home#index",
      :protocol => (Rails.application.config.force_ssl ? "https://" : "http://"),
      :as => "root"

    get "/rss" => "home#index", :format => "rss"
    get "/hottest" => "home#index", :format => "json"

    get "/page/:page" => "home#index"

    get "/newest" => "home#newest", :format => /html|json|rss/
    get "/newest/page/:page" => "home#newest"
    get "/newest/:user" => "home#newest_by_user"
    get "/newest/:user/page/:page" => "home#newest_by_user"
    get "/recent" => "home#recent"
    get "/recent/page/:page" => "home#recent"
    get "/hidden" => "home#hidden"
    get "/hidden/page/:page" => "home#hidden"

    get "/upvoted(.format)" => "home#upvoted"
    get "/upvoted/page/:page" => "home#upvoted"

    get "/top" => "home#top"
    get "/top/page/:page" => "home#top"
    get "/top/:length" => "home#top"
    get "/top/:length/page/:page" => "home#top"

    get "/threads" => "comments#threads"
    get "/threads/:user" => "comments#threads"

    get "/login" => "login#index"
    post "/login" => "login#login"
    post "/logout" => "login#logout"

    get "/signup" => "signup#index"
    post "/signup" => "signup#signup"
    get "/signup/invite" => "signup#invite"

    get "/login/forgot_password" => "login#forgot_password",
      :as => "forgot_password"
    post "/login/reset_password" => "login#reset_password",
      :as => "reset_password"
    match "/login/set_new_password" => "login#set_new_password",
      :as => "set_new_password", :via => [:get, :post]

    get "/t/:tag" => "home#tagged", :as => "tag", :format => /html|rss/
    get "/t/:tag/page/:page" => "home#tagged"

    get "/search" => "search#index"
    get "/search/:q" => "search#index"

    resources :stories do
      post "upvote"
      post "downvote"
      post "unvote"
      post "undelete"
      post "hide"
      post "unhide"
    end
    post "/stories/fetch_url_attributes", :format => "json"
    post "/stories/preview" => "stories#preview"

    resources :comments do
      member do
        get "reply"
        post "upvote"
        post "downvote"
        post "unvote"

        post "delete"
        post "undelete"
      end
    end
    get "/comments/page/:page" => "comments#index"
    get "/comments" => "comments#index", :format => /html|rss/

    get "/messages/sent" => "messages#sent"
    post "/messages/batch_delete" => "messages#batch_delete",
      :as => "batch_delete_messages"
    resources :messages do
      post "keep_as_new"
    end

    get "/s/:id/:title/comments/:comment_short_id" => "stories#show"
    get "/s/:id/(:title)" => "stories#show", :format => /html|json/

    get "/c/:id" => "comments#redirect_from_short_id"

    get "/u" => "users#tree"
    get "/u/:username" => redirect { |params| "@#{params[:username]}" }
    get "/@:username" => "users#show", :as => "user", :format => /html|json/

    get "/settings" => "settings#index"
    post "/settings" => "settings#update"
    post "/settings/pushover" => "settings#pushover"
    get "/settings/pushover_callback" => "settings#pushover_callback"
    post "/settings/delete_account" => "settings#delete_account",
      :as => "delete_account"

    get "/filters" => "filters#index"
    post "/filters" => "filters#update"

    post "/invitations" => "invitations#create"
    get "/invitations" => "invitations#index"
    get "/invitations/request" => "invitations#build"
    post "/invitations/create_by_request" => "invitations#create_by_request",
      :as => "create_invitation_by_request"
    get "/invitations/confirm/:code" => "invitations#confirm_email"
    post "/invitations/send_for_request" => "invitations#send_for_request",
      :as => "send_invitation_for_request"
    get "/invitations/:invitation_code" => "signup#invited"
    post "/invitations/delete_request" => "invitations#delete_request",
      :as => "delete_invitation_request"

    get "/moderations" => "moderations#index"
    get "/moderations/page/:page" => "moderations#index"

    get "/privacy" => "home#privacy"
    get "/about" => "home#about"

    if defined?(BbsController) || Rails.env.development?
      get "/bbs" => "bbs#index"
    end
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  before_filter :require_logged_in_user_or_400,
    :only => [ :upvote, :downvote, :unvote, :hide, :unhide, :preview ]

  before_filter :require_logged_in_user, :only => [ :destroy, :create, :edit,
    :fetch_url_title, :new ]

  before_filter :find_user_story, :only => [ :destroy, :edit, :undelete,
    :update ]

  def create
    @title = "Submit Story"
    @cur_url = "/stories/new"

    @story = Story.new(story_params)
    @story.user_id = @user.id

    if @story.valid? && !(@story.already_posted_story && !@story.seen_previous)
      if @story.save
        Countinual.count!("#{Rails.application.shortname}.stories.submitted",
          "+1")

        return redirect_to @story.comments_path
      end
    end

    return render :action => "new"
  end

  def destroy
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = true
    @story.editor = @user

    if params[:reason].present? && @story.user_id != @user.id
      @story.moderation_reason = params[:reason]
    end

    @story.save(:validate => false)

    redirect_to @story.comments_path
  end

  def edit
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @title = "Edit Story"

    if @story.merged_into_story
      @story.merge_story_short_id = @story.merged_into_story.short_id
    end
  end

  def fetch_url_attributes
    s = Story.new
    s.fetching_ip = request.remote_ip
    s.url = params[:fetch_url]

    oattrs = { :url => params[:fetch_url], :title => nil }

    if (title = s.fetched_title).present?
      oattrs[:title] = title
    end

    if (cu = s.fetched_canonical_url).present?
      oattrs[:url] = cu
    end

    return render :json => oattrs
  end

  def new
    @title = "Submit Story"
    @cur_url = "/stories/new"

    @story = Story.new
    @story.fetching_ip = request.remote_ip

    if params[:url].present?
      @story.url = params[:url]

      if (cu = @story.fetched_canonical_url).present? && @story.url != cu
        flash.now[:notice] = "Note: URL has been changed to fetched " <<
          "canonicalized version"
        @story.url = cu
      end

      if s = Story.find_similar_by_url(@story.url)
        if s.is_recent?
          # user won't be able to submit this story as new, so just redirect
          # them to the previous story
          flash[:success] = "This URL has already been submitted recently."
          return redirect_to s.comments_path
        else
          # user will see a warning like with preview screen
          @story.already_posted_story = s
        end
      end

      # ignore what the user brought unless we need it as a fallback
      @story.title = @story.fetched_title
      if !@story.title.present? && params[:title].present?
        @story.title = params[:title]
      end
    end
  end

  def preview
    @story = Story.new(story_params)
    @story.user_id = @user.id
    @story.previewing = true

    @story.vote = Vote.new(:vote => 1)
    @story.upvotes = 1

    @story.valid?

    @story.seen_previous = true

    return render :action => "new", :layout => false
  end

  def show
    @story = Story.where(:short_id => params[:id]).first!

    if @story.merged_into_story
      flash[:success] = "\"#{@story.title}\" has been merged into this story."
      return redirect_to @story.merged_into_story.comments_path
    end

    if @story.can_be_seen_by_user?(@user)
      @title = @story.title
    else
      @title = "[Story removed]"
    end

    @short_url = @story.short_id_url

    @comments = @story.merged_comments.includes(:user, :story,
      :hat).arrange_for_user(@user)

    if params[:comment_short_id]
      @comments.each do |c,x|
        if c.short_id == params[:comment_short_id]
          c.highlighted = true
          break
        end
      end
    end

    respond_to do |format|
      format.html {
        @comment = @story.comments.build

        load_user_votes

        render :action => "show"
      }
      format.json {
        render :json => @story.as_json(:with_comments => @comments)
      }
    end
  end

  def undelete
    if !(@story.is_editable_by_user?(@user) &&
    @story.is_undeletable_by_user?(@user))
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user
    @story.save(:validate => false)

    redirect_to @story.comments_path
  end

  def update
    if !@story.is_editable_by_user?(@user)
      flash[:error] = "You cannot edit that story."
      return redirect_to "/"
    end

    @story.is_expired = false
    @story.editor = @user

    if @story.url_is_editable_by_user?(@user)
      @story.attributes = story_params
    else
      @story.attributes = story_params.except(:url)
    end

    if @story.save
      return redirect_to @story.comments_path
    else
      return render :action => "edit"
    end
  end

  def unvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(0, story.id,
      nil, @user.id, nil)

    render :text => "ok"
  end

  def upvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(1, story.id,
      nil, @user.id, nil)

    render :text => "ok"
  end

  def downvote
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    if !Vote::STORY_REASONS[params[:reason]]
      return render :text => "invalid reason", :status => 400
    end

    if !@user.can_downvote?(story)
      return render :text => "not permitted to downvote", :status => 400
    end

    Vote.vote_thusly_on_story_or_comment_for_user_because(-1, story.id,
      nil, @user.id, params[:reason])

    render :text => "ok"
  end

  def hide
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    HiddenStory.hide_story_for_user(story.id, @user.id)

    render :text => "ok"
  end

  def unhide
    if !(story = find_story)
      return render :text => "can't find story", :status => 400
    end

    HiddenStory.where(:user_id => @user.id, :story_id => story.id).delete_all

    render :text => "ok"
  end

private

  def story_params
    p = params.require(:story).permit(
      :title, :url, :description, :moderation_reason, :seen_previous,
      :merge_story_short_id, :is_unavailable, :tags_a => [],
    )

    if @user.is_moderator?
      p
    else
      p.except(:moderation_reason, :merge_story_short_id, :is_unavailable)
    end
  end

  def find_story
    story = Story.where(:short_id => params[:story_id]).first
    if @user && story
      story.vote = Vote.where(:user_id => @user.id,
        :story_id => story.id, :comment_id => nil).first.try(:vote)
    end

    story
  end

  def find_user_story
    if @user.is_moderator?
      @story = Story.where(:short_id => params[:story_id] || params[:id]).first
    else
      @story = Story.where(:user_id => @user.id, :short_id =>
        (params[:story_id] || params[:id])).first
    end

    if !@story
      flash[:error] = "Could not find story or you are not authorized " <<
        "to manage it."
      redirect_to "/"
      return false
    end
  end

  def load_user_votes
    if @user
      if v = Vote.where(:user_id => @user.id, :story_id => @story.id,
      :comment_id => nil).first
        @story.vote = { :vote => v.vote, :reason => v.reason }
      end

      @story.is_hidden_by_cur_user = @story.is_hidden_by_user?(@user)

      @votes = Vote.comment_votes_by_user_for_story_hash(@user.id, @story.id)
      @comments.each do |c|
        if @votes[c.id]
          c.current_vote = @votes[c.id]
        end
      end
    end
  end
end

app/helpers/stories_helper.rb
module StoriesHelper
  def show_guidelines?
    if !@user
      return true
    end

    if @user.stories_submitted_count <= 5
      return true
    end

    if Moderation.joins(:story).
    where("stories.user_id = ? AND moderations.created_at > ?", @user.id,
    5.days.ago).count > 0
      return true
    end

    false
  end

  def show_story_embed(story, args = {})
    embedder = Hcxp::Embedder.embed_html_for(story.url, args)

    if embedder.present?
      content_tag :div, embedder.html_safe, class: 'story-embed'
    end
  end
end

app/views/stories/_form.html.erb
<% if f.object.errors.count == 1 && f.object.already_posted_story %>
  <div class="alert alert-danger">
    <h4>Error: This story was already submitted <%=
      time_ago_in_words(f.object.already_posted_story.created_at) %> ago</h2>
    <p>
      Please view the <a href="<%= f.object.already_posted_story.comments_path %>"
      target="_blank">previous discussion</a> for this story.
    </p>
  </div>
<% elsif f.object.errors.any? %>
  <%= render 'global/form_errors', object: f.object %>
  <%- error_messages_for f.object %>
<% elsif !f.object.errors.any? && f.object.already_posted_story %>
  <div class="alert alert-info">
  <h4>Note: This story was already submitted <%=
    time_ago_in_words(f.object.already_posted_story.created_at) %> ago, but may
    be submitted again.</h2>
  <p>
  Please view the <a href="<%= f.object.already_posted_story.comments_path %>"
  target="_blank">previous discussion</a> for this story first.  If the content
  has changed or warrants new discussion, you may submit it again.
  </p>
  </div>

  <%= f.hidden_field :seen_previous %>
<% end %>

<div class="form-horizontal">
  <div class="form-group">
  <% if f.object.url_is_editable_by_user?(@user) %>
    <%= f.label :url, "URL:", :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <div class="row">
        <div class="col-sm-10">
          <%= f.text_field :url, :autocomplete => "off", class: 'form-control' %>
        </div>

        <div class="col-sm-2">
          <%= button_tag "Fetch Title", class: 'btn btn-default btn-block', :id => "story_fetch_title",
            :type => "button" %>
        </div>
      </div>
    </div>
  <% elsif !f.object.new_record? && !f.object.url.blank? %>
    <%= f.label :url, "URL:", :class => "control-label required" %>
    <div class="form-input">
      <a href="<%= f.object.url %>"><%= f.object.url %></a>
    </div>
  <% end %>
  </div>

  <div class="form-group">
    <%= f.label :title, "Title:", :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <%= f.text_field :title, :maxlength => 100, :autocomplete => "off", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
  <%= f.label :tags_a, "Tags:", :class => "col-sm-2 control-label required",
    :style => "line-height: 2.3em;" %>
  <div class="col-sm-10">
    <%= f.select "tags_a", options_for_select(
      Tag.all_with_filtered_counts_for(@user).map{|t|
        html = "<strong>#{h(t.tag)}</strong> - #{h(t.description.to_s)}"

        if t.hotness_mod != 0
          html << " (hotness mod #{t.hotness_mod > 0 ? "+" : ""}#{t.hotness_mod})"
        end
        if t.filtered_count > 0
          html << " <em>#{t.filtered_count} user" <<
            (t.filtered_count == 1 ? "" : "s") << " filtering</em>"
        end

        [ "#{t.tag} - #{t.description}", t.tag, { "data-html" => raw(html) } ]},
      f.object.tags_a), {}, { :multiple => true } %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, "Text:", :class => "col-sm-2 control-label required" %>
    <div class="col-sm-10">
      <%= f.text_area :description, :rows => 15,
        :placeholder => "Optional when submitting a URL; please see guidelines",
        :autocomplete => "off", class: 'form-control' %>
    </div>
  </div>

  <div class="form-group markdown_help_toggler">
    <div class="col-sm-10 col-sm-offset-2">
      <p><a href="#" id="story_guidelines_toggler">
        Story submission guidelines
      </a></p>

      <div id="story_guidelines" style="<%= show_guidelines?? "" :
      "display: none;" %>">
        <div style="float: right;">
        <a href="javascript:window.location=%22<%= Rails.application.root_url %>stories/new?url=%22+encodeURIComponent(document.location)+%22&title=%22+encodeURIComponent(document.title)"
        style="border: 1px solid #ddd; padding: 0.5em; background-color:
        #f8f8f8; line-height: 1.5em; margin-left: 1em;">Submit to
        <%= Rails.application.name %></a>
        </div>
        <ul>

          <li><p>
          To be able to easily submit a page you're viewing in your browser
          to <%= Rails.application.name %>, drag the bookmarklet to the right
          to your bookmark bar.  You'll be taken to this page with the viewed
          page's URL and title.
          </p></li>

          <li><p>
          When submitting a URL, the text field is optional and should only
          be used when additional context or explanation of the URL is
          needed.  Commentary or opinion should be reserved for a comment,
          so that it can be voted on separately from the story.
          </p></li>

          <li><p>
          Do not editorialize story titles, but when the original story's
          title has no context or is unclear, please change it.  <strong>Please
          remove extraneous components from titles such as the name of the
          site or section.</strong>
          </p></li>

          <li><p>
          If no tags clearly apply to the story you are submitting, chances
          are it does not belong here.  Do not overreach with tags if they
          are not the primary focus of the story.
          </p></li>

          <li><p>
          When the story being submitted is more than a year or so old,
          please add the year the story was written to the post title in
          [brackets].
          </p></li>

        </ul>
      </div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function() {
    $("#story_fetch_title").click(function() {
      Lobsters.fetchURLTitle($(this), $("#story_url"), $("#story_title"));
      return false;
    });
  });
</script>

app/views/stories/_listdetail.html.erb
<li id="story_<%= story.short_id %>" data-shortid="<%= story.short_id %>"
class="media story <%= story.vote && story.vote[:vote] == 1 ? "upvoted" : "" %>
<%= story.vote && story.vote[:vote] == -1 ? "downvoted" : "" %>
<%= story.is_hidden_by_cur_user ? "hidden" : "" %>
<%= story.is_expired? ? "expired" : "" %>">

  <div class="media-left">
    <div class="vote story-vote cursor-pointer">
      <% if @user %>
        <a class="upvoter"></a>
      <% else %>
        <%= link_to "", login_path, :class => "upvoter" %>
      <% end %>
      <div class="score"><%= story.score %></div>
    </div>
  </div>

  <% if story.thumb.present? %>
    <a class="story-thumb media-left" href="<%= story.comments_path %>">
      <%= image_tag story.thumb.url, size: '49x49', class: 'img-rounded' %>
    </a>
  <% end %>

  <div class="media-body">
    <% if story.can_be_seen_by_user?(@user) %>
      <a class='story-heading' href="<%= story.url_or_comments_path %>"><%=
        break_long_words(story.title) %></a>
    <% end %>
    <% if story.is_gone? %>
      [Story removed by <%= story.is_moderated? ? "moderator" :
        "original submitter" %>]
    <% end %>

    <% if story.can_be_seen_by_user?(@user) %>
      <span class="tags">
        <% story.sorted_taggings.each do |tagging| %>
          <a href="<%= tag_path(tagging.tag.tag) %>"
            class="<%= tagging.tag.css_class %>"
            title="<%= tagging.tag.description %>"><%= tagging.tag.tag %></a>
        <% end %>
      </span>
      <% if story.domain.present? %>
        <small>
        <a class="domain text-muted" href="<%= story.domain_search_url %>"><%=
          break_long_words(story.domain) %></a>
        </small>
      <% end %>

      <% if defined?(single_story) && single_story %>
        <% story.merged_stories.each do |ms| %>
          <br>
          <span class="merge"></span>
          <span class="link">
            <a href="<%= ms.url_or_comments_path %>"><%=
              break_long_words(ms.title) %></a>
          </span>
          <span class="tags">
            <% ms.sorted_taggings.each do |tagging| %>
              <a href="<%= tag_path(tagging.tag.tag) %>"
                class="<%= tagging.tag.css_class %>"
                title="<%= tagging.tag.description %>"><%= tagging.tag.tag %></a>
            <% end %>
          </span>
          <% if ms.domain.present? %>
            <a class="domain" href="<%= ms.domain_search_url %>"><%=
              break_long_words(ms.domain) %></a>
          <% end %>
          <span class="byline">
            by
            <a href="/u/<%= ms.user.username %>"
            <% if ms.user.is_new? %>
              class="new_user"
            <% end %>><%= ms.user.username %></a>

            <% if @user && @user.show_avatars? %>
              <img src="<%= ms.user.avatar_url(16) %>" width="16" height="16" class="avatar">
            <% end %>

            <%= time_ago_in_words_label(ms.created_at, :strip_about => true) %>
              ago
          </span>
        <% end %>
      <% end %>
    <% end %>

    <div class="story-byline">
      <ul class="list-inline">
      <% if story.previewing %>
        <li>
        by
        <a><%= story.user.username %></a>
        <% if @user && @user.show_avatars? %>
          <img src="<%= story.user.avatar_url(16) %>" width="16" height="16" class="avatar">
        <% end %>
        </li>

        <li>
        just now
        </li>
      <% else %>
        <li>
        by
        <a href="/u/<%= story.user.username %>"
        <% if story.user.is_new? %>
          class="new_user"
        <% end %>><%= story.user.username %></a>

        <% if @user && @user.show_avatars? %>
          <img src="<%= story.user.avatar_url(16) %>" class="avatar">
        <% end %>
        </li>

        <li>
        <a href="<%= story.comments_path %>"><%= time_ago_in_words_label(story.created_at, :strip_about => true) %>
          ago</a>
        </li>

        <% if story.is_editable_by_user?(@user) %>
          <li>
          <a href="<%= edit_story_path(story.short_id) %>">edit</a>
          </li>

          <% if story.is_gone? && story.is_undeletable_by_user?(@user) %>
            <li>
            <%= link_to "undelete", story_undelete_path(story.short_id),
              :method => :post, :data => {
              :confirm => "Are you sure you want to undelete this story?" } %>
            </li>
          <% elsif !story.is_gone? %>
            <% if story.user_id != @user.try(:id) &&
            @user.try(:is_moderator?) %>
            <li>
              <%= link_to "delete", story_path(story.short_id),
                :method => :delete, :class => "mod_story_link" %>
            </li>
            <% else %>
              <li>
              <%= link_to "delete", story_path(story.short_id),
                :method => :delete, :data => {
                :confirm => "Are you sure you want to delete this story?" } %>
              </li>
            <% end %>
          <% end %>
        <% end %>
        <% if !story.is_gone? && @user %>
          <% if @user && story.vote && story.vote[:vote] == -1 %>
            <li><a class="flagger">unflag (<%=
              Vote::STORY_REASONS[story.vote[:reason]].to_s.downcase %>)</a></li>
          <% elsif @user && @user.can_downvote?(story) %>
            <li><a class="flagger cursor-pointer">flag</a></li>
          <% end %>
          <% if story.is_hidden_by_cur_user %>
            <li><%= link_to "unhide", story_unhide_path(story.short_id),
              :class => "hider" %></li>
          <% else %>
            <li><%= link_to "hide", story_hide_path(story.short_id),
              :class => "hider" %></li>
          <% end %>
          <% if defined?(single_story) && single_story && story.hider_count > 0 %>
            <li>(hidden by <%= pluralize(story.hider_count, "user") %>)</li>
          <% end %>
        <% end %>
        <% if !story.is_gone? && (@user || story.comments_count > 0) %>
            <li>
            <a href="<%= story.comments_path %>"><%= story.comments_count == 0 ?
              "discuss" : "#{story.comments_count} comment" <<
              (story.comments_count == 1 ? "" : "s") %></a></li>
        <% end %>

        <% if defined?(single_story) && single_story %>
          <% if story.downvotes > 0 %>
            | <%= story.vote_summary_for(@user).downcase %>
          <% end %>
        <% end %>
      <% end %>
      </ul>
    </div>
  </div>
<div class="mobile_comments <%= story.comments_count == 0 ? "zero" : "" %>"
style="display: none;">
  <a href="<%= story.comments_path %>"><%= story.comments_count %></a>
</div>
</li>

app/views/stories/edit.html.erb
<div class="box" id="story_box">
  <div class="legend">
    Edit Story
  </div>

  <%= form_for @story, :url => story_path(@story.short_id),
  :method => :put, :html => { :id => "edit_story" } do |f| %>
    <%= render :partial => "stories/form", :locals => { :story => @story,
      :f => f } %>

    <% if @user.is_moderator? %>
      <div class="box">
        <div class="boxline">
          <%= f.label :merge_story_short_id, "Merge Into:",
            :class => "required" %>
          <%= f.text_field :merge_story_short_id, :autocomplete => "off",
            :placeholder => "Short id of story into which this story " <<
            "be merged" %>
        </div>
        <div class="boxline">
          <%= f.label :unavailable_at, "Unavailable:",
            :class => "required" %>
          <%= f.check_box :is_unavailable %>
          <%= f.label :unavailable_at, "Source URL is unavailable, " <<
            "enable display of cached text", :class => "normal" %>
        </div>
        <% if @story.user_id != @user.id %>
          <div class="boxline">
            <%= f.label :moderation_reason, "Mod Reason:",
              :class => "required" %>
            <%= f.text_field :moderation_reason, :autocomplete => "off" %>
          </div>
        <% end %>
      </div>
    <% end %>

    <p></p>

    <div class="box">
      <div class="boxline markdown_help_toggler">
        <div class="markdown_help_label">
          Markdown formatting available
        </div>

        <%= submit_tag "Save" %>
        &nbsp;or <a href="<%= story_path(@story.short_id) %>">cancel
          editing</a>

        <div style="clear: both;"></div>

        <%= render :partial => "global/markdownhelp",
          :locals => { :allow_images => true } %>
      </div>
    </div>
  <% end %>
</div>

app/views/stories/new.html.erb
<div class="col-sm-12">
  <div class="box" id="story_box">
    <h1 class="legend">
      Submit a Story
    </h1>

    <br/>

    <div id="story_holder">
      <%= form_for @story do |f| %>
        <%= render :partial => "stories/form", :locals => { :story => @story,
          :f => f } %>

        <div class="row">
          <div class="col-sm-4 col-sm-offset-2">
            <%= submit_tag "Submit", class: 'btn btn-primary' %>
            <button type="button" class="btn btn-default story-preview">Preview</button>
          </div>

          <div class="col-sm-6 text-right markdown_help_toggler">
            <p class="markdown_help_label">
              Markdown formatting available
            </p>

            <%= render :partial => "global/markdownhelp",
              :locals => { :allow_images => true } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>

  <div id="story_preview">
    <% if @story.previewing && @story.valid? %>
      <%= render :template => "stories/show" %>
    <% end %>
  </div>

  <script>
    $(document).ready(function() {
      <% if @story.previewing %>
        $("#story_tags_a").select2({
          formatSelection: function(what) {
            return what.id;
          }
        });
      <% else %>
        $("#story_url").focus();
      <% end %>
    });
  </script>
</div>

app/views/stories/show.html.erb
<div class="col-sm-12">
  <ol class="stories list-unstyled">
    <%= render :partial => "stories/listdetail",
      :locals => { :story => @story, :single_story => true } %>
  </ol>

  <div class="story_content">

    <%= show_story_embed(@story, width: '100%') %>

    <% if @story.markeddown_description.present? %>
      <div class="story_text">
        <%=h story_markdown(@story.description) %>
      </div>
    <% end %>

    <% if @story.is_unavailable && @story.story_cache.present? %>
      <a id="story_text_expander">Source URL considered unavailable as of <%=
      time_ago_in_words_label(@story.unavailable_at) %> ago, cached text
      available</a>
      <div id="collapsed_story_text">
        <p>
        <em>All story content copyright of its respective owner.</em>
        </p>

        <div class="story_text">
          <blockquote>
            <%= simple_format(@story.story_cache) %>
          </blockquote>
        </div>
      </div>

      <script>
        document.getElementById("story_text_expander").addEventListener("click",
          function() {
            document.getElementById("collapsed_story_text").style.display = "block";
            return false;
          });
      </script>
    <% end %>
  </div>

  <% if !@story.previewing %>
    <ol class="comments comments1 list-unstyled">
      <% if !@story.is_gone? && !@story.previewing %>
        <li><%= render "comments/commentbox", :comment => @comment %></li>
      <% end %>

      <% comments_by_parent = @comments.group_by(&:parent_comment_id) %>
      <% subtree = comments_by_parent[nil] %>
      <% ancestors = [] %>

      <% while subtree %>
        <% if (comment = subtree.shift) %>
          <li>
          <%= render "comments/comment", :comment => comment,
            :show_story => (comment.story_id != @story.id),
            :was_merged => (comment.story_id != @story.id) %>

          <% if (children = comments_by_parent[comment.id]) %>
            <% ancestors << subtree %>
            <% subtree = children %>
            <ol class="comments">
          <% else %>
            <ol class="comments"></ol></li>
          <% end %>
        <% elsif (subtree = ancestors.pop) %>
          </ol></li>
        <% end %>
      <% end %>
    </ol>
  <% end %>
</div>